### ISSUE TITLE
"Accept: *" header can result in hung request.

### ISSUE THREAD

**Issue by NatalieWolfe** [restify/node-restify#1008]
When a request has an `Accept` header with the value `*` Restify behaves... erratically. Below you can see one test case which shows how the `req.accepts` method improperly denies `*` matching any mime types.

If you take this example and change the line `res.json({message: 'foo'});` to `res.send({message: 'foo'});` then the request will silently hang with no errors being thrown or messages logged.

And further, in a server for work, a request with the `Accept: *` header will receive a 406 Not Acceptable response when the server uses `res.send({...})` and in our tests such requests will receive literally the string `[object Object]` instead of a JSON-formatted value. I have not yet been able to reproduce these two issues in isolation however.

I would expect the header `Accept: *` to be functionally equivalent to `Accept: */*` and indicate that _any_ response format is acceptable.

**accepts.js**
```js
var restify = require('restify');
var server = restify.createServer();

server.get('/', function(req, res, next){
    try {
        console.log('Accept:', req.header('Accept'));
        console.log('\ttext/plain', req.accepts('text/plain'));
        console.log('\ttext/html', req.accepts('text/html'));
        console.log('\tapplication/json', req.accepts('application/json'));
        console.log('\thtml', req.accepts('html'));
        console.log('\tjson', req.accepts('json'));
    }
    catch (err) {
        console.log('Error testing accepts:', err.stack);
    }

    res.json({message: 'foo'});
    next();
});

server.listen(8080);
```

**server output**
```sh
$ node accepts.js
Accept: text/*
	text/plain text/plain
	text/html text/html
	application/json undefined
	html text/html
	json undefined
Accept: text/html
	text/plain undefined
	text/html text/html
	application/json undefined
	html text/html
	json undefined
Accept: application/*
	text/plain undefined
	text/html undefined
	application/json application/json
	html undefined
	json application/json
Accept: application/json
	text/plain undefined
	text/html undefined
	application/json application/json
	html undefined
	json application/json
Accept: *
	text/plain undefined
	text/html undefined
	application/json undefined
	html undefined
	json undefined
Accept: */*
	text/plain text/plain
	text/html text/html
	application/json application/json
	html text/html
	json application/json
```

**requests**
```sh
$ curl http://localhost:8080 -H 'Accept: text/*' && echo ""
{"message":"foo"}
$ curl http://localhost:8080 -H 'Accept: text/html' && echo ""
{"message":"foo"}
$ curl http://localhost:8080 -H 'Accept: application/*' && echo ""
{"message":"foo"}
$ curl http://localhost:8080 -H 'Accept: application/json' && echo ""
{"message":"foo"}
$ curl http://localhost:8080 -H 'Accept: *' && echo ""
{"message":"foo"}
$ curl http://localhost:8080 -H 'Accept: */*' && echo ""
{"message":"foo"}
```

**Comment by DonutEspresso** [comment]
Thanks for the code snippets - I took a look and think there are two things at play here.

First, `*` is not a valid media type AFAICT from the HTTP spec, so that's probably why `req.accepts()` is not returning you the correct value. 

Second, regarding the missing responses for text/html, restify doesn't ship with a text/html formatter, so you'll have to add one, i.e.,

```js
var server = restify.createServer({
  formatters: {
    'text/html': function(req, res, body, cb) {
      // body here is the {message: 'foo'} from res.send()
      // so format it however you think it should be sent back, i.e.,
      var out = '<!doctype html><html><body>' + body.message + '</body></html>';
      return cb(null, out);
    }
  }
});
```

For the request with `Accept: *`, because `accepts()` matches none of the known media types, it won't even attempt to call a formatter, and will instead just return a 406.

**Comment by NatalieWolfe** [comment]
RE: `text/html`, that was only in the test to round it out. I don't actually care about it.

The real concern, as mentioned in the issue subject and in my third sentence, is that `Accept: *` when using `res.send({message: 'foo'})` instead of `res.json` **the request will hang**.

While `*` may not be a valid content type as listed in the HTTP spec, people do use it. In this case it was encountered by our endpoint for push notifications from our subscription services provider, so it is _not_ something we can control or change.

**Comment by NatalieWolfe** [comment]
I realize now that my test case as presented is too cluttered, here's a simplified one:

**accept.js**
```js
var restify = require('restify');
var server = restify.createServer();

server.get('/', function(req, res, next){
    res.send({message: 'foo'});
    next();
});

server.listen(8080);
```

**interaction**
```sh
$ node accept.js &
[1] 28228
$ time curl http://localhost:8080/ -H 'Accept: *'
^C

real    0m11.590s
user    0m0.006s
sys     0m0.007s
$ time curl http://localhost:8080/ -H 'Accept: */*'
{"message":"foo"}
real    0m0.068s
user    0m0.005s
sys     0m0.008s
```

From this example it is made quite clear: the request is hanging when it receives the `Accept: *` header.

**Comment by DonutEspresso** [comment]
Ah, apologies - turns out we've fixed this in 4.x head but have not yet published a new version. The issue was first [reported here](https://github.com/restify/node-restify/issues/937). 

I'll publish 4.0.4 shortly.

**Comment by DonutEspresso** [comment]
Just published 4.0.4 Give it a try and let me know if you're still seeing problems.

**Comment by NatalieWolfe** [comment]
Cool, the behavior now is... better. But still not great.

```sh
$ time curl http://localhost:9001/ -H 'Accept: *'

real	0m0.013s
user	0m0.003s
sys 	0m0.003s
$ time curl http://localhost:9001/ -H 'Accept: */*'
{"message":"foo"}
real	0m0.012s
user	0m0.003s
sys 	0m0.003s
```

The hanging part is clearly resolved, which was my main concern. Should I close this and create a separate one for treating `*` the same as `*/*`?

**Comment by yunong** [comment]
Yes please. Thanks for letting us know!

**Comment by NatalieWolfe** [comment]
Closing, duplicate of #937. Will open a separate ticket for the `*` vs `*/*` issue.
